server:
  port: 8443
spring:
  application:
    name: wj
  datasource:
    #url: jdbc:h2:mem:test
    url: jdbc:h2:file:D:/develop/mywork/wj/db/test
    driver-class-name: org.h2.Driver
    username: sa
    password: 123456
    #data: classpath:db/data.sql  #进行该配置后，每次启动程序，程序都会运行resources/db/data.sql文件，对数据库的数据操作。
    #schema: classpath:db/schema.sql #进行该配置后，每次启动程序，程序都会运行resources/db/schema.sql文件，对数据库的结构进行操作。
    platform: h2  #表明使用的数据库平台是h2
  jpa:
      database: h2
      hibernate:
        ddl-auto: update
      show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true



